"""changes image type to largrBinary

Revision ID: b97c37ba7579
Revises: 7aaca7053855
Create Date: 2025-01-24 17:37:18.024712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97c37ba7579'
down_revision = '7aaca7053855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products',
        'image',
        type_=sa.LargeBinary(),
        postgresql_using='image::bytea'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products',
        'image',
        type_=sa.VARCHAR(length=255),
    )

    # ### end Alembic commands ###
