"""added role column to the user table

Revision ID: 488fe1e6bfa6
Revises: 182e359c6fcd
Create Date: 2025-01-23 19:39:47.308734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488fe1e6bfa6'
down_revision = '182e359c6fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
