"""renamed categories column

Revision ID: d4ce37e2a277
Revises: b97c37ba7579
Create Date: 2025-01-24 18:23:04.067009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ce37e2a277'
down_revision = 'b97c37ba7579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('products_Cartegories_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['categories_id'], ['id'])
        batch_op.drop_column('Cartegories_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cartegories_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_Cartegories_id_fkey', 'categories', ['Cartegories_id'], ['id'])
        batch_op.drop_column('categories_id')

    # ### end Alembic commands ###
